### ISSUE TITLE
how can i use farwest

### ISSUE THREAD

**Issue by leeyisoft** [ninenines/farwest#1]
how can i use it, plase give me same document like this https://ninenines.eu/docs/en/cowboy/2.8/guide/getting_started/

**Comment by essen** [comment]
Check the tests or the talk given at fosdem 2020. Right now the development reached the first milestone (discovery of resources) but is not complete. Work on the second milestone (discovery of operations) will begin soon.

**Comment by essen** [comment]
I'll close this for now. Please follow the project to stay informed. Thanks!
